<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="Serilog" Version="4.3.1" />
  </ItemGroup>

	<ItemGroup>
		<Folder Include="Validators\Announcements\" />
		<ProjectReference Include="..\RevampWebSTTB.Contracts\RevampWebSTTB.Contracts.csproj" />
		<ProjectReference Include="..\RevampWebSTTB.Entities\RevampWebSTTB.Entities.csproj" />
		<Folder Include="RequestHandlers\Announcements\" />
	</ItemGroup>



</Project>
